name: CI

on:
  push:
    branches:
      - master

env:
  TURBO_TELEMETRY_DISABLED: 1

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup turborepo cache
        uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build apps
        run: pnpm build

      - name: Publish packages to NPM
        shell: bash
        run: |
          echo "//registry.npmjs.org/:_authToken="${{ secrets.NPM_TOKEN }}"" > ~/.npmrc
          pnpm -r --filter='./apps/*' publish --access public --provenance
